version: "3.8"
services:
  db:
    image: postgres:13
    container_name: voting-app-db
    environment:
      POSTGRES_USER: voting
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voting-app
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: voting-app-adminer
    ports:
      - "8080:8080"  # Changed from 5000 to 8080
    depends_on:
      - db

volumes:
  postgres-data: